name: sanity-check

on:
    [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        
    steps:
        run: whoami
        run: id
        run: google-chrome --version
        run: chromedriver --version 
        